x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "myAwEsOm3pa55@w0rd"
  POSTGRES_USER: "user"

x-rabbitmq-variables: &x-rabbitmq-variables
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "admin"

x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: "1"
  APP_NAME: "go-clean-template"
  APP_VERSION: "1.0.0"
  HTTP_PORT: "8001"
  HTTP_USE_PREFORK_MODE: "false"
  LOG_LEVEL: "debug"
  PG_POOL_MAX: "2"
  PG_URL: "postgres://user:myAwEsOm3pa55@w0rd@auth-db:5432/db"
  GRPC_PORT: "9001"
  RMQ_RPC_SERVER: "rpc_server"
  RMQ_RPC_CLIENT: "rpc_client"
  RMQ_URL: "amqp://admin:admin@rabbitmq:5672/"
  METRICS_ENABLED: "true"
  SWAGGER_ENABLED: "true"

services:
  db:
    container_name: auth-db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      app_network:
        aliases:
          - db.lvh.me

  app:
    container_name: auth-app
    platform: linux/amd64
    build:
      context: .
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8001:8001"
      - "9001:9001"
    depends_on:
      - db
    networks:
      app_network:
        aliases:
          - app.lvh.me
      apisix:
        aliases:
          - auth-app

  nginx:
    container_name: auth-nginx
    image: nginx:1.29-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:80"
    depends_on:
      - app
    networks:
      app_network:
        aliases:
          - nginx.lvh.me
      apisix:
        aliases:
          - nginx.lvh.me

networks:
  app_network:
    external: false
  apisix:
    external: true

volumes:
  db_data:
